init_state: [-4, 0, 0]                     
goal: [4, 0, 0]                           
dt: 0.1                                   
ped_model: "HSFM"                         
total_peds: 7                             
ped_detc_range: 3                         
ped_detc_fov: 120                         
misdetection_prob: 0                      
is_robot_visible: False                   
tollerence_error: 0.1                     
waypoint_tracker: "fixed"                 
pedestrians_init_states: [                
  [ 4.0,  0.0,  0.0],                     
  [ 0, -4,  0],
  [ 0,  4,  0],
  [ 2.82,  2.82, 0],
  [-2.82, -2.82, 0],
  [ 2.82, -2.82, 0],
  [-2.82,  2.82, 0]
]
pedestrians_goals: [                       
  [[-4.0,  0.0]],                          
  [[ 0,  4]],
  [[ 0, -4]],
  [[-2.82, -2.82]],
  [[ 2.82,  2.82]],
  [[-2.82,  2.82]],
  [[ 2.82, -2.82]]
]