# Robot Model: Unicycle Model with State Vector: [x, y, phi]
# Pedestrian Model: Velocity Propagation with State Vector: [x, y, vx, vy] inside MPC propagation and SFM for simulator

# General
X_rob_init: [2, 0, 0]                  # Initial robot state vector: [x_rob_init, y_rob_init, phi_rob_init], [m, m, rad, m/s, rad/s]
p_rob_ref:  [0, 0, 0]                  # Reference robot position: [x_rob_ref,  y_rob_ref,  phi_rob_ref], [m, m, rad]
dt: 0.1                                 # Time interval, [s]
n_horizon: 30                           # MPC planning horizon, [steps]
Q: [[10000, 0, 0],
    [0, 10000, 0],
    [0,   0,   1]]                      # State weighted matrix: [dx, dy, dphi]
R: [[1, 0],
    [0, 1]]                             # Control input weighted matrix: [u_a, u_alpha], [m/s^2, rad/s^2]
r_rob: 0.35                             # Robot radius, [m]
r_ped: 0.3                              # Pedestrian radius, [m]
simulation_time: 20                     # Simulation time, [s]
lb: [0, 0]                             # Lower bounds for NLP: [v, w, u_a, u_alpha], [m/s, rad/s]
ub: [2, 2]                              # Upper bounds for NLP: [v, w, u_a, u_alpha], [m/s, rad/s]
min_safe_dist: 0.5                      # Minimum safe distance to pedestrians and other objects, [m]
total_peds: 1                           # Amount of pedestrians
ped_dect_range: 4                       # Pedestrian detector max range, [m]
ped_dect_fov: 120                       # Pedestrian detector max fov, [deg] 
misdetection_prob: 0.3                  # Probability of pedestrian misdetection
x_dummy_ped: [10000, 10000, 0, 0]       # Dummy pedestrian state vector: [x_ped,  y_ped, vx_ped, vy_ped], [m, m, m/s, m/s]
is_robot_visible: True                  # Boolean flag of robot visibility for pedestrians 

# Graphics
annotation_offset: [0, 0.2]             # Offset for annotation: [x, y]
col_hex: ['#1f77b4',                    # HEX Colors that used for visualization
          '#ff7f0e',
          '#2ca02c', 
          '#d62728', 
          '#9467bd', 
          '#8c564b', 
          '#e377c2', 
          '#7f7f7f', 
          '#bcbd22', 
          '#17becf']
animation_format: '.gif'                # Animation format: .gif, .mp4