# Robot Model, [model_type]:
#       1. Unicycle Model with State Vector: [x, y, phi], Control Vector: [v, w]
#       2. Unicycle Double Integration Model with State Vector: [x, y, phi, v, w], Control Vector: [u_a, u_alpha]

# Pedestrian Model for the controller, [ped_predictor]:
#       1. Constant Velocity Propagation with State Vector: [x, y, vx, vy]
#       2. Neural Predictor (work in progress)

# Pedestrian pyminisim model:
#       1. Headed Social Force Model (HSFM)
#       2. Optimal Reciprocal Collision Avoidance (ORCA)

init_state: [0, 0, 0]                     # Initial robot state vector: [x, y, phi] [m, m, rad] for "unicycle" model_type and  [x, y, phi, v, w] [m, m, rad, m/s, rad/s] for "unicycle_double_integrator" model_type
goal: [4, -1, 0]                            # Reference robot position: [x,  y,  phi], [m, m, rad]
dt: 0.05                                    # Time interval, [s]
horizon: 63                                # MPC planning horizon, [steps]
model_type: "unicycle"                     # Robot model, ["unicycle", "unicycle_double_integrator"]
ped_model: "ORCA"                          # Pedestrian pyminisim model, ["HSFM", "ORCA"]
ped_predictor: "constant_velocity"                    # Pedestrian predictor, ["constant_velocity", "neural"]
Q: [[10, 0, 0],
    [0, 10, 0],
    [0,   0,   1]]                         # State weighted matrix: [dx, dy, dphi]
R: [[0.005, 0],
    [0, 0.005]]                                # Control input weighted matrix
q_b: 0.0
q_m: 0.001
r_rob: 0.35                                # Robot radius, [m]
r_ped: 0.3                                 # Pedestrian radius, [m]
min_safe_dist: 0.05                           # Minimum safe distance to pedestrians and other objects, [m]
n_iterations: 100
alpha: 0.001

total_peds: 1                              # Amount of pedestrians
ped_detc_range: 8                          # Pedestrian detector max range, [m]
ped_detc_fov: 120                          # Pedestrian detector max fov, [deg]
misdetection_prob: 0                       # Probability of pedestrian misdetection
is_robot_visible: False                     # Boolean flag of robot visibility for pedestrians
tollerance_error: 0.1                      # Tollernce error for the Euclidean distance to the goal, [m]
is_store_robot_predicted_trajectory: True  # Flag to store robot predicted trajectory, [True, False]
max_ghost_tracking_time: 20                # Amount of steps to track ghost pedestrian, [step]
waypoint_tracker: "fixed"                  # Choose a waypoint tracker for pedestrians: ["random", "fixed"]
pedestrians_init_states: [                 # Only for "fixed" waypoint_tracker
  [ 2.,  0,  0]                            # Provide initial states of the pedestrians according to the amount specified in total_peds, [x, y, phi], [m, m, rad]
]
pedestrians_goals: [                       # Only for "fixed" waypoint_tracker
  [[2,  0]],                              # Provide goals for the pedestrians according to the amount specified in total_peds, [x, y], [m, m]
]


state_dummy_ped: [10000, 10000, 0, 0]      # Dummy pedestrian state vector: [x_ped,  y_ped, vx_ped, vy_ped], [m, m, m/s, m/s]
