dt: 0.1                         
goal:                           
- -2.8689696766651043 
- 2.737023962343015
- -0.0
init_state:                      
- 2.8689696766651043
- -2.737023962343015
- 0.0
is_robot_visible: false         
misdetection_prob: 0            
ped_detc_fov: 120                
ped_detc_range: 3                
ped_model: HSFM                  
pedestrians_goals:               
- - - -1.794211367304542          
    - -3.378998153064259
pedestrians_init_states:         
- - 1.794211367304542             
  - 3.378998153064259
  - 0.0
tollerance_error: 0.1            
total_peds: 1                    
waypoint_tracker: fixed                                         