dt: 0.1                         
goal:                           
- 0
- 4
- -0.0
init_state:                      
- 0
- -4
- 1.57
is_robot_visible: false         
misdetection_prob: 0            
ped_detc_fov: 120                
ped_detc_range: 3                
ped_model: HSFM             
pedestrians_goals:               
- - - 0          
    - -4
pedestrians_init_states:         
- - 0          
  - 4
  - 0.0
tolerance_error: 0.1            
total_peds: 1                    
waypoint_tracker: fixed                                         